export const DEFAULT_BRANDS = [
  { name: 'Chevrolet' },
  { name: 'Volkswagen' },
  { name: 'Fiat' },
  { name: 'Hyundai' },
  { name: 'Toyota' },
  { name: 'Jeep' },
  { name: 'Renault' },
  { name: 'Honda' },
  { name: 'Nissan' },
  { name: 'Ford' },
  { name: 'Peugeot' },
  { name: 'Citroën' },
  { name: 'Mitsubishi' },
  { name: 'Caoa Chery' },
  { name: 'BMW' },
  { name: 'Mercedes-Benz' },
  { name: 'Audi' },
  { name: 'Volvo' },
  { name: 'Kia' },
  { name: 'Land Rover' }
];

export const DEFAULT_MODELS = [
  { brand: 'Chevrolet', name: 'Onix' },
  { brand: 'Chevrolet', name: 'Onix Plus' },
  { brand: 'Chevrolet', name: 'Tracker' },
  { brand: 'Chevrolet', name: 'Spin' },
  { brand: 'Chevrolet', name: 'S10' },
  { brand: 'Volkswagen', name: 'Gol' },
  { brand: 'Volkswagen', name: 'Polo' },
  { brand: 'Volkswagen', name: 'T-Cross' },
  { brand: 'Volkswagen', name: 'Virtus' },
  { brand: 'Fiat', name: 'Argo' },
  { brand: 'Fiat', name: 'Mobi' },
  { brand: 'Fiat', name: 'Strada' },
  { brand: 'Fiat', name: 'Toro' },
  { brand: 'Hyundai', name: 'HB20' },
  { brand: 'Hyundai', name: 'HB20S' },
  { brand: 'Hyundai', name: 'Creta' },
  { brand: 'Toyota', name: 'Corolla' },
  { brand: 'Toyota', name: 'Corolla Cross' },
  { brand: 'Toyota', name: 'Hilux' },
  { brand: 'Jeep', name: 'Renegade' },
  { brand: 'Jeep', name: 'Compass' },
  { brand: 'Renault', name: 'Kwid' },
  { brand: 'Renault', name: 'Duster' },
  { brand: 'Honda', name: 'Civic' },
  { brand: 'Honda', name: 'City' },
  { brand: 'Nissan', name: 'Kicks' },
  { brand: 'Nissan', name: 'Versa' },
  { brand: 'Ford', name: 'Ka' },
  { brand: 'Ford', name: 'EcoSport' },
  { brand: 'Peugeot', name: '208' },
  { brand: 'Citroën', name: 'C3' },
  { brand: 'Mitsubishi', name: 'L200' },
  { brand: 'Caoa Chery', name: 'Tiggo 5x' },
  { brand: 'Caoa Chery', name: 'Tiggo 7' },
  { brand: 'BMW', name: '320i' },
  { brand: 'Audi', name: 'A3' },
  { brand: 'Volvo', name: 'XC60' },
  { brand: 'Kia', name: 'Sportage' },
  { brand: 'Land Rover', name: 'Range Rover Evoque' }
];

export const DEFAULT_COLORS = [
  { name: 'Branco' },
  { name: 'Preto' },
  { name: 'Prata' },
  { name: 'Cinza' },
  { name: 'Vermelho' },
  { name: 'Azul' },
  { name: 'Verde' },
  { name: 'Marrom' },
  { name: 'Bege' },
  { name: 'Amarelo' },
  { name: 'Laranja' },
  { name: 'Vinho' },
  { name: 'Grafite' },
  { name: 'Dourado' },
  { name: 'Rosa' }
];
