export const DEFAULT_BRANDS = [
  { name: 'Chevrolet' },
  { name: 'Volkswagen' },
  { name: 'Fiat' },
  { name: 'Hyundai' },
  { name: 'Toyota' },
  { name: 'Jeep' },
  { name: 'Renault' },
  { name: 'Honda' },
  { name: 'Nissan' },
  { name: 'Ford' },
  { name: 'Peugeot' },
  { name: 'Citroën' },
  { name: 'Mitsubishi' },
  { name: 'Caoa Chery' },
  { name: 'BMW' },
  { name: 'Mercedes-Benz' },
  { name: 'Audi' },
  { name: 'Volvo' },
  { name: 'Kia' },
  { name: 'Land Rover' }
];

export const DEFAULT_MODELS = [
  { brand: 'Chevrolet', name: 'Onix' },
  { brand: 'Chevrolet', name: 'Onix Plus' },
  { brand: 'Chevrolet', name: 'Tracker' },
  { brand: 'Chevrolet', name: 'Spin' },
  { brand: 'Chevrolet', name: 'S10' },
  { brand: 'Chevrolet', name: 'Celta' },
  { brand: 'Volkswagen', name: 'Gol' },
  { brand: 'Volkswagen', name: 'Polo' },
  { brand: 'Volkswagen', name: 'T-Cross' },
  { brand: 'Volkswagen', name: 'Virtus' },
  { brand: 'Volkswagen', name: 'Jetta' },
  { brand: 'Chevrolet', name: 'Montana' },
  { brand: 'Chevrolet', name: 'Cruze' },
  { brand: 'Chevrolet', name: 'Cruze Sport6' },
  { brand: 'Chevrolet', name: 'Equinox' },
  { brand: 'Chevrolet', name: 'Trailblazer' },
  { brand: 'Chevrolet', name: 'Prisma' },
  { brand: 'Chevrolet', name: 'Cobalt' },
  { brand: 'Chevrolet', name: 'Camaro' },
  { brand: 'Volkswagen', name: 'Saveiro' },
  { brand: 'Volkswagen', name: 'Nivus' },
  { brand: 'Volkswagen', name: 'Taos' },
  { brand: 'Volkswagen', name: 'Amarok' },
  { brand: 'Volkswagen', name: 'Fox' },
  { brand: 'Volkswagen', name: 'up!' },
  { brand: 'Volkswagen', name: 'Voyage' },
  { brand: 'Volkswagen', name: 'Golf' },
  { brand: 'Fiat', name: 'Cronos' },
  { brand: 'Fiat', name: 'Pulse' },
  { brand: 'Fiat', name: 'Fastback' },
  { brand: 'Fiat', name: 'Fiorino' },
  { brand: 'Fiat', name: 'Grand Siena' },
  { brand: 'Fiat', name: 'Palio' },
  { brand: 'Fiat', name: 'Doblo' },
  { brand: 'Hyundai', name: 'Tucson' },
  { brand: 'Hyundai', name: 'ix35' },
  { brand: 'Hyundai', name: 'Santa Fe' },
  { brand: 'Toyota', name: 'Yaris' },
  { brand: 'Toyota', name: 'Yaris Sedan' },
  { brand: 'Toyota', name: 'SW4' },
  { brand: 'Toyota', name: 'RAV4 Hybrid' },
  { brand: 'Toyota', name: 'Etios' },
  { brand: 'Toyota', name: 'Etios Sedan' },
  { brand: 'Toyota', name: 'Prius' },
  { brand: 'Jeep', name: 'Commander' },
  { brand: 'Jeep', name: 'Wrangler' },
  { brand: 'Renault', name: 'Sandero' },
  { brand: 'Renault', name: 'Logan' },
  { brand: 'Renault', name: 'Oroch' },
  { brand: 'Renault', name: 'Captur' },
  { brand: 'Renault', name: 'Kardian' },
  { brand: 'Honda', name: 'HR-V' },
  { brand: 'Honda', name: 'CR-V Hybrid' },
  { brand: 'Honda', name: 'Fit' },
  { brand: 'Honda', name: 'WR-V' },
  { brand: 'Honda', name: 'Accord' },
  { brand: 'Nissan', name: 'Sentra' },
  { brand: 'Nissan', name: 'Frontier' },
  { brand: 'Nissan', name: 'X-Trail e-Power' },
  { brand: 'Nissan', name: 'March' },
  { brand: 'Ford', name: 'Ranger' },
  { brand: 'Ford', name: 'Maverick' },
  { brand: 'Ford', name: 'Bronco Sport' },
  { brand: 'Ford', name: 'Territory' },
  { brand: 'Ford', name: 'Mustang' },
  { brand: 'Peugeot', name: '2008' },
  { brand: 'Peugeot', name: '3008' },
  { brand: 'Peugeot', name: '5008' },
  { brand: 'Peugeot', name: 'Landtrek' },
  { brand: 'Peugeot', name: 'Partner Rapid' },
  { brand: 'Citroën', name: 'C4 Cactus' },
  { brand: 'Citroën', name: 'C3 Aircross' },
  { brand: 'Citroën', name: 'Aircross (antiga)' },
  { brand: 'Mitsubishi', name: 'L200 Triton' },
  { brand: 'Mitsubishi', name: 'Outlander' },
  { brand: 'Mitsubishi', name: 'ASX' },
  { brand: 'Mitsubishi', name: 'Pajero Sport' },
  { brand: 'Caoa Chery', name: 'Tiggo 3x' },
  { brand: 'Caoa Chery', name: 'Tiggo 8' },
  { brand: 'Caoa Chery', name: 'Tiggo 8 Pro' },
  { brand: 'Caoa Chery', name: 'Arrizo 6' },
  { brand: 'Caoa Chery', name: 'iCar' },
  { brand: 'BMW', name: 'X1' },
  { brand: 'BMW', name: 'X3' },
  { brand: 'BMW', name: 'X5' },
  { brand: 'Audi', name: 'Q3' },
  { brand: 'Audi', name: 'Q5' },
  { brand: 'Audi', name: 'A4' },
  { brand: 'Volvo', name: 'XC40' },
  { brand: 'Volvo', name: 'C40' },
  { brand: 'Volvo', name: 'XC90' },
  { brand: 'Kia', name: 'Sorento' },
  { brand: 'Kia', name: 'K3' },
  { brand: 'Kia', name: 'Cerato' },
  { brand: 'Kia', name: 'Niro' },
  { brand: 'Kia', name: 'EV6' },
  { brand: 'Land Rover', name: 'Discovery Sport' },
  { brand: 'Land Rover', name: 'Defender' },
  { brand: 'Land Rover', name: 'Range Rover Velar' },
  { brand: 'Subaru', name: 'Crosstrek (XV)' },
  { brand: 'Subaru', name: 'Forester' },
  { brand: 'Subaru', name: 'Outback' },
  { brand: 'RAM', name: 'Rampage' },
  { brand: 'RAM', name: '1500' },
  { brand: 'RAM', name: '2500' },
  { brand: 'RAM', name: '3500' },
  { brand: 'BYD', name: 'Dolphin' },
  { brand: 'BYD', name: 'Dolphin Mini' },
  { brand: 'BYD', name: 'Yuan Plus (Atto 3)' },
  { brand: 'BYD', name: 'Song Plus' },
  { brand: 'BYD', name: 'Seal' },
  { brand: 'BYD', name: 'Tan' },
  { brand: 'GWM', name: 'Haval H6' },
  { brand: 'GWM', name: 'Haval H6 GT' },
  { brand: 'GWM', name: 'Ora 03' },
  { brand: 'GWM', name: 'Poer' },
  { brand: 'JAC', name: 'E-JS1' },
  { brand: 'JAC', name: 'T40 Plus' },
  { brand: 'JAC', name: 'T60 Plus' },
  { brand: 'Suzuki', name: 'Jimny' },
  { brand: 'Suzuki', name: 'Jimny Sierra' },
  { brand: 'Suzuki', name: 'Vitara' },
  { brand: 'Suzuki', name: 'S-Cross' },
  { brand: 'Mercedes-Benz', name: 'A 200' },
  { brand: 'Mercedes-Benz', name: 'GLA' },
  { brand: 'Mercedes-Benz', name: 'GLB' },
  { brand: 'Mercedes-Benz', name: 'GLC' },
  { brand: 'Mercedes-Benz', name: 'C 200' },
  { brand: 'Mini', name: 'Cooper' },
  { brand: 'Porsche', name: 'Macan' },
  { brand: 'Fiat', name: 'Argo' },
  { brand: 'Fiat', name: 'Mobi' },
  { brand: 'Fiat', name: 'Strada' },
  { brand: 'Fiat', name: 'Toro' },
  { brand: 'Fiat', name: 'Siena' },
  { brand: 'Fiat', name: 'Uno' },
  { brand: 'Fiat', name: 'Palio' },
  { brand: 'Fiat', name: 'Linea' },
  { brand: 'Hyundai', name: 'HB20' },
  { brand: 'Hyundai', name: 'HB20S' },
  { brand: 'Hyundai', name: 'Creta' },
  { brand: 'Toyota', name: 'Corolla' },
  { brand: 'Toyota', name: 'Corolla Cross' },
  { brand: 'Toyota', name: 'Hilux' },
  { brand: 'Jeep', name: 'Renegade' },
  { brand: 'Jeep', name: 'Compass' },
  { brand: 'Renault', name: 'Kwid' },
  { brand: 'Renault', name: 'Duster' },
  { brand: 'Honda', name: 'Civic' },
  { brand: 'Honda', name: 'City' },
  { brand: 'Nissan', name: 'Kicks' },
  { brand: 'Nissan', name: 'Versa' },
  { brand: 'Ford', name: 'Ka' },
  { brand: 'Ford', name: 'EcoSport' },
  { brand: 'Peugeot', name: '208' },
  { brand: 'Citroën', name: 'C3' },
  { brand: 'Mitsubishi', name: 'L200' },
  { brand: 'Caoa Chery', name: 'Tiggo 5x' },
  { brand: 'Caoa Chery', name: 'Tiggo 7' },
  { brand: 'BMW', name: '320i' },
  { brand: 'Audi', name: 'A3' },
  { brand: 'Volvo', name: 'XC60' },
  { brand: 'Kia', name: 'Sportage' },
  { brand: 'Land Rover', name: 'Range Rover Evoque' }
];

export const DEFAULT_COLORS = [
  { name: 'Branco' },
  { name: 'Preto' },
  { name: 'Prata' },
  { name: 'Cinza' },
  { name: 'Vermelho' },
  { name: 'Azul' },
  { name: 'Verde' },
  { name: 'Marrom' },
  { name: 'Bege' },
  { name: 'Amarelo' },
  { name: 'Laranja' },
  { name: 'Vinho' },
  { name: 'Grafite' },
  { name: 'Dourado' },
  { name: 'Rosa' }
];
