export const DEFAULT_SERVICES = [
  { name: 'Pintura automotiva para-choque' },
  { name: 'Pintura automotiva para-lamas' },
  { name: 'Pintura automotiva capô' },
  { name: 'Pintura automotiva teto' },
  { name: 'Pintura automotiva porta' },
  { name: 'Pintura automotiva porta-malas' },
  { name: 'Polimento' },
  { name: 'Vitrificação' },
  { name: 'Retoque de pintura' },
  { name: 'Funilaria leve' },

  // acrescentados
  { name: 'Funilaria média' },
  { name: 'Funilaria pesada' },
  { name: 'Pintura automotiva lateral completa' },
  { name: 'Pintura automotiva geral' },
  { name: 'Pintura automotiva retrovisores' },
  { name: 'Pintura automotiva maçanetas' },
  { name: 'Pintura automotiva rodas' },
  { name: 'Pintura automotiva pinças de freio' },
  { name: 'Pintura automotiva teto em black piano' },
  { name: 'Pintura automotiva grade e frisos' },
  { name: 'Pintura automotiva colunas (A/B/C)' },
  { name: 'Repintura parcial (spot repair)' },
  { name: 'Descontaminação com clay bar' },
  { name: 'Polimento técnico 1 etapa' },
  { name: 'Polimento técnico 2 etapas' },
  { name: 'Polimento técnico 3 etapas' },
  { name: 'Espelhamento' },
  { name: 'Cristalização de pintura' },
  { name: 'Vitrificação de vidros' },
  { name: 'Ceramic coating 9H' },
  { name: 'Restauração de faróis' },
  { name: 'Higienização interna' },
  { name: 'Higienização com ozônio' },
  { name: 'Lavagem técnica' },
  { name: 'Martelinho de ouro (PDR)' },
  { name: 'Remoção de amassados por granizo' },
  { name: 'Solda plástica em para-choque' },
  { name: 'Reparo em fibra de vidro' },
  { name: 'Alinhamento de portas e para-lamas' },
  { name: 'Substituição de para-choque' },
  { name: 'Substituição de para-lamas' },
  { name: 'Substituição de porta' },
  { name: 'Envelopamento parcial (teto/retrovisores)' },
  { name: 'Envelopamento total' },
  { name: 'Aplicação de PPF (proteção de pintura) – parcial' },
  { name: 'Aplicação de PPF (proteção de pintura) – total' },
  { name: 'Remoção de riscos leves' },
  { name: 'Correção de cor com espectrofotômetro' },
  { name: 'Remoção de adesivos e cola' },
  { name: 'Pintura personalizada (faixas/duas cores)' },
  { name: 'Retoque de rodas (arranhões/calas)' }
];
